import math
from datetime import date, timedelta
import pytest
from smw.model.decay import (
    DOW_WEIGHTS, blended_wow, day_weight, decay_sigma, project_decay,
)

FRI_MAY_1 = date(2026, 5, 1)  # 2026-05-01 is a Friday

def test_dow_weights_sum_to_one():
    assert math.isclose(sum(DOW_WEIGHTS), 1.0)

def test_day_weight_week_one_uses_dow_week_two_uniform():
    assert day_weight(FRI_MAY_1, 0) == DOW_WEIGHTS[4]   # release Friday
    assert day_weight(FRI_MAY_1, 1) == DOW_WEIGHTS[5]   # Saturday
    assert day_weight(FRI_MAY_1, 9) == pytest.approx(1 / 7)

def test_sigma_taper():
    assert decay_sigma(0) == 0.30
    assert decay_sigma(6) == 0.10
    assert decay_sigma(3) == pytest.approx(0.30 - 0.20 * 3 / 6)
    assert decay_sigma(10) == 0.10

def _synthetic_cumulative(week_1, wow, release, upto):
    days = (upto - release).days
    return sum(week_1 * wow ** (d // 7) * day_weight(release, d) for d in range(days))

def test_back_calibration_round_trips(season):
    # A film generated by pure geometric decay must project to its own full-window total.
    week_1, wow = 100_000_000.0, 0.55
    today = FRI_MAY_1 + timedelta(days=24)  # mid-week, partial week 4
    cumulative = _synthetic_cumulative(week_1, wow, FRI_MAY_1, today)
    full = _synthetic_cumulative(week_1, wow, FRI_MAY_1,
                                 season.window_end + timedelta(days=1))
    median, _ = project_decay(cumulative, FRI_MAY_1, wow, season, today)
    assert median == pytest.approx(full, rel=1e-9)

def test_pre_release_date_raises(season):
    with pytest.raises(ValueError):
        project_decay(1.0, date(2026, 7, 1), 0.55, season, date(2026, 6, 30))

def test_frozen_past_window_end(season):
    median, _ = project_decay(500.0, FRI_MAY_1, 0.55, season, season.window_end)
    assert median == 500.0

def test_degenerate_day_zero_projects_from_week_two(season):
    median, sigma = project_decay(50_000_000.0, FRI_MAY_1, 0.5, season, FRI_MAY_1)
    assert median > 50_000_000.0
    assert sigma == 0.30
    # cumulative treated as week one; remaining tail is week_1 * (w + w^2 + ...)
    expected_tail = sum(
        50_000_000.0 * 0.5 ** (d // 7) * day_weight(FRI_MAY_1, d)
        for d in range(7, (season.window_end - FRI_MAY_1).days + 1)
    )
    assert median == pytest.approx(50_000_000.0 + expected_tail)

def test_blend_defaults_below_three_snapshots():
    d = date(2026, 6, 1)
    assert blended_wow([], 0.55) == 0.55
    assert blended_wow([(d, 100.0)], 0.55) == 0.55
    assert blended_wow([(d, 100.0), (d + timedelta(days=7), 150.0)], 0.55) == 0.55

def test_blend_pulls_toward_observed():
    d = date(2026, 6, 1)
    obs = [(d, 100.0), (d + timedelta(days=7), 180.0), (d + timedelta(days=14), 220.0)]
    # deltas 80, 40 → ratio 0.5; weight 2/5 → 0.4*0.5 + 0.6*0.55 = 0.53
    assert blended_wow(obs, 0.55) == pytest.approx(0.53)

def test_blend_full_weight_at_six_snapshots():
    d = date(2026, 6, 1)
    obs = [(d + timedelta(days=7 * i), 100.0 * (2 - 0.5 ** i)) for i in range(6)]
    ratios_only = blended_wow(obs, 0.99)
    assert ratios_only == pytest.approx(0.5, rel=1e-6)  # default contributes nothing

def test_clamp_growth_cannot_exceed_one():
    # §13.5 named gap: grosses that grew between observations must clamp to ≤ 1.0.
    d = date(2026, 6, 1)
    obs = [(d, 100.0), (d + timedelta(days=7), 150.0),
           (d + timedelta(days=14), 260.0), (d + timedelta(days=21), 500.0),
           (d + timedelta(days=28), 1000.0), (d + timedelta(days=35), 3000.0)]
    assert blended_wow(obs, 0.55) <= 1.0

def test_zero_delta_pairs_skipped():
    d = date(2026, 6, 1)
    obs = [(d, 100.0), (d + timedelta(days=7), 100.0), (d + timedelta(days=14), 100.0)]
    assert blended_wow(obs, 0.55) == 0.55  # no positive-delta pairs → default
